### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by waliarubal** [amazerol/AvaloniaRibbon#2]
Hello,

I was looking for a ribbon control for Avalonia for a long time and came across your project. I have a couple of questions.

Firstly, Is this production ready?

Can I use this with 0.9.x branch of Avalonia which is  in kind of preview?

Can't see code base for Ribbon to check the implementation. Is that in a separate repository which ain't listed here?

Can I use it with my application https://github.com/waliarubal/Jaya which I am trying to make like Windows Explorer? I Would like to replace the menu and toolbar of my app with a stable ribbon control.

**Comment by waliarubal** [comment]
Seems like this project is abandoned now!

**Comment by HankG** [comment]
@waliarubal I used this for some mocking up stuff and it worked well enough.  I haven't used it since though.  I can't say whether it's abandoned or the developer isn't on GitHub all the time.  They did update to 0.8.2 two months ago. I have an app I'm going to be trying it out against potentially in the near future...

**Comment by waliarubal** [comment]
@HankG Thanks for the info. Do you have the code base for the control or the repository's URL where its hosted? Maybe I can carry forward to maintain it.

**Comment by HankG** [comment]
I thought this project had everything but now that I look at the csproj I see that it's the wrong type...now I'm not sure :(.  Can try pinging him on Gitter...

**Comment by waliarubal** [comment]
@HankG If he is on gitter, please do ping him. I feel he has put considerable efforts in this control which should be used and improved.

**Comment by amazerol** [comment]
Hello !
Sorry about disappearing from github but I newly created my company and I had to spend time on it !
The project in not at all dead ! It was just ... let's say ... in standby.
To answer all your questions :
- This is production ready since I am using it for one of my project. But in fact, it depends on how demanding you are. I already have some improvements in mind, I just don't have the time for that now.
- for version 0.9.x, I haven't tried it so I cannot guarantee anything.
- I'll make the code public so you can all have a look at it. I'll probably use a MIT licence or something like that so everyone can have fun with it without being annoyed by copyleft things of GPL.
And, of course, you are very welcome to use it with your interesting app !

**Comment by waliarubal** [comment]
@amazerol Thanks for the update. I am still looking forward for you to put up the code in public so it can be tinkered with.

**Comment by amazerol** [comment]
hmmm, this is already set to public ... I am missing something in my github settings ?

**Comment by waliarubal** [comment]
Can see your code for ribbon now. Can see a lot of code behind though, it made me think that logics were missing. Will fork the repo and turn it into a proper control gallery. Thanks for the cool stuff.
